### ISSUE TITLE
Pseudogene annotation

### ISSUE THREAD

**Issue by fmalmeida** [ShiuLab/PseudogenePipeline#2]
Hello,

I would like to confirm the Pseudogene annotation process. When giving as input a set of genes of interest that I'd like to check for pseudogenes, the pipeline checks wheter the input genes themselves are pseudogenes or not? Or it only check for "new" pseudogenes in the entire genome?

**Comment by shinhanshiu** [comment]
Hi Felipe,
> I have a seto genes of interest which I would like to predict pseudogenes -- TARGET.fa, in the parameter file, this is ˋp_seqˋ parameter right?

If your TARGET.fa is the nucleotide sequence you'd like to predict pseudogenes from, it is the g_seq.

p_seq is the protein sequence file you used as query.
> Also, the ˋtblastnˋ I should do is the genome itself against this TARGET.fa, correct?

If your TARGET.fa is the nucleotide sequence you'd like to predict pseudogenes from, then it is the reverse.

It is tBLASTn so protein sequences against a database of nucleotide sequences.
> The main question is: The gff file must have the complete annotation, of all the genes in the genome or only the entries of the genes present in the TARGET.fa? The gff should be a COMPLETE.gff or TARGET.gff?

Just need the annotations for entries in your TARET.fa.

**Comment by fmalmeida** [comment]
Thank you for this thorough response.

It really helps.
